# Generated by Django 4.1.13 on 2024-02-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
